### ISSUE TITLE
Merging Across Intersections with Low Class Roads

### ISSUE THREAD

**Issue by drewda** [opentraffic/osmlr#11]
from @dnesbitt61:

![osmlr edge cases - google docs 2017-02-09 10-21-01](https://cloud.githubusercontent.com/assets/212369/22796983/75e2e598-eeb1-11e6-824f-e60d63992928.png)

There are several cases where OSMLR segments should be merged across intersections where only “intersecting roads” meeting specific criteria exist. Possibilities include:

- Non driveable roads (e.g., walkways)
- Emergency Access Only
- Private Access (e.g. driveways)
- Service roads
- Any local road (discuss implications!)

**Comment by drewda** [comment]
from @zerebubuth:

> Non driveable roads (e.g., walkways)

Currently, the code will refuse to merge across any node which has an edge which crosses between levels. A better strategy might be to follow those edges and see where they lead, although this adds some complexity to the already-complex merging code.

> discuss implications!

I think the main problem with this would be that we don't get a measurement for any segment which has been partially driven. Therefore, it makes sense to omit some local roads, but also to ensure that the segment is terminated frequently enough that we don't lose too much data.

**Comment by dnesbitt61** [comment]
Latest code merged will merge edges that only connect to "local" roads when creating OSMLR segments. This dramatically reduces the number of short (<20m) OSMLR segments. To address @zerebubuth 's concern about not getting reports as frequently we should limit the length of an OSMLR segment.
