### ISSUE TITLE
Internal Intersection Edges

### ISSUE THREAD

**Issue by drewda** [opentraffic/osmlr#13]
from @dnesbitt61:

“Internal” edges are the edges between doubly digitized, separated carriageways that allow turns onto an intersecting road. In the image below it is the section of McGaw Road between the 2 separate carriageways of Snowden River Parkway. In reality these are often just large intersections. 

![osmlr edge cases - google docs 2017-02-09 10-54-47](https://cloud.githubusercontent.com/assets/212369/22798275/2dcd59e6-eeb6-11e6-993b-eba935ec38c2.png)

Thought:

Traces that cross an internal intersection should somehow apply transition costs when going from one OSMLR segment onto another but should not actually be represented as a separate OSMLR segment.

**Comment by dnesbitt61** [comment]
Internal intersection edges are now skipped when creating OSMLR segments.
