### ISSUE TITLE
Roundabouts

### ISSUE THREAD

**Issue by drewda** [opentraffic/osmlr#14]
from @dnesbitt61:

![osmlr edge cases - google docs 2017-02-09 10-55-25](https://cloud.githubusercontent.com/assets/212369/22798309/44ec9470-eeb6-11e6-9898-663bfaf918a0.png)

Roundabouts generally contain several short Valhalla edges. Creating a separate OSMLR segment for each might not be the best way to represent a roundabout.  Perhaps roundabouts are best ignored during OSMLR creation and the figure into the transition costs between OSMLR segments during routing?

**Comment by drewda** [comment]
from @zerebubuth:

> Creating a separate OSMLR segment for each might not be the best way to represent a roundabout

It seems that this issue (and #13) are really related to generalising the network graph. By omitting the roundabout (or internal edges) we lose implicit connectivity. Perhaps it is worth making that explicit, and storing in the OSMLR tiles what the possible subsequent segments for any given segment are?

**Comment by dnesbitt61** [comment]
Roundabouts are currently skipped when creating OSMLR segments.
