### ISSUE TITLE
Oneway and Side of Street Driving Information

### ISSUE THREAD

**Issue by dnesbitt61** [opentraffic/osmlr#17]
GeoJSON (and perhaps pbf) could use 2 additional pieces of information to help with visualization:

Oneway - Flag indicating whether the segment is oneway travel or allows travel in both directions. This can be useful for logic that produces "offset geometry".
Side of Street Driving - Does the segment indicate drive on right (default) or drive on left. This also is important for producing offset geometry.

**Comment by drewda** [comment]
Added in #19
