### ISSUE TITLE
Consider Generating OSMLR Tiles to Include Residential Roads

### ISSUE THREAD

**Issue by dnesbitt61** [opentraffic/osmlr#23]
This would create OSMLR segment definitions on Valhalla level 2 (local tiles). 

Questions and Issues:

- Which road classifications to include: residential, unclassified, service, footways and cycleways?

- Does this mean that OSMLR segments on arterials and highways should be split when crossing OSMLR segments on the local level? This would create a large increase in the number of OSMLR segments and would create a large number of short segments (which may cause accuracy issues and could complicate traffic influenced routing).

- Note on Sizing: 60% of the Valhalla graph edges are on the local hierarchy level - so creating OSMLR segments for these would dramatically increase the OSMLR data size (and Valhalla tiles if association to OSMLR segments is required on level 2).

**Comment by drewda** [comment]
//cc @kpwebb @nvkelso

**Comment by nvkelso** [comment]
+1 for adding `residential`, `unclassified`, `service`.

How much extra space would adding `track`, `path`, `footway` and `cycleway` take up? Don't think those are necessary for a purely Open(car)Traffic use-case.

**Comment by dnesbitt61** [comment]
A quick test for Philippines without any code optimizations for level 2 (OSMLR creation program already allows specifying lowest level or largest value in the Valhalla hierarchy to generate OSMLR segments for):

Level 0,1 only (merge across intersections with level 2 roads): 243,266 (3916 of which are < 25m)
Level 0,1,2 (merge 0,1 across intersections with level 2 roads): 1,897,814 (136,662 of which are < 25m)

This is a significant increase in the count of OSMLR segments (many of which are very short). At level 2, basically every Valhalla edge becomes an OSMLR segment (and those > 1km are split into multiple segments).

**Comment by dnesbitt61** [comment]
Also, looks like adding path, footway, cycleway is only a marginal increase above adding driveable service, residential, and unclassified roads. For Philippines this adds an extra 20,453 OSMLR segments. Perhaps other countries where these ways are more prevalent would see a higher increase, but I think it is still small when compared with the driveable level 2 roads.

**Comment by dnesbitt61** [comment]
Some more stats:

Edge counts for driveways and cul-de-sacs (these are likely candidates to remove from OSMLR). Parking could also be a candidate for removal/non-inclusion in OSMLR.

driveways: 12118
cul-de-sacs: 50498
parking: 8368

**Comment by dnesbitt61** [comment]
Ran OSMLR for Local Hierarchy on a planet-wide Valhalla tile set. Includes driveable unclassified and residential roads. Will merge edges (road segments) across service/other roads (includes driveways, parking, footways, cycleways, etc.) and non-driveable edges. This also excludes any road use other than road or ramp: e.g., cul-de-sacs.

Planet-wide OSMLR for levels 0 (highway) and 1 (arterial):

- count = **37107371** shortsegs = 654366 longsegs 1
- chunks 17428372
- average length = 462.977
- Max OSMLR segments within a tile = 155691
- Average OSMLR count per tile = 2761
- Tile count = 13438

Total edges on Level 0 and 1: 137959046 - about 1 OSMLR segment per 4 edges.

OSMLR Planet: levels: 0, 1, 2 (unclassified and residential only):

- count = **213453304** shortsegs = 10098039 longsegs 4
- chunks 35839134
- average length = 80.4855
- Max OSMLR segments within a tile = 343476
- Average OSMLR count per tile = 1522
- Tile count = 140206

Total run time is about 30 minutes over all 3 tile levels.

**Comment by dnesbitt61** [comment]
GeoJSON for the Planet is 88GB (67 GB for level 2).
