### ISSUE TITLE
Set up data creation environment for traffic.

### ISSUE THREAD

**Issue by gknisely** [opentraffic/osmlr#26]
We need to set up a self sustaining data creation environment.  Thinking that we can use valhalla docker scripts.  Should be able to use the following scripts for this environment:

`scripts/minutely_update.sh` -- Applies changesets to the latest planet.pbf file. Should be set up to run forever via lamdba.
`scripts/associate_segments.sh` -- runs valhalla_associate_segments on valhalla data using the latest osmlr...thinking it can run once a week.
`scripts/cut_tiles.sh` -- creates valhalla route tiles. Should be set up to run forever via lamdba.

We need to discuss as we are thinking that the results of minutely_update.sh should be saved in a mount point and cut_tiles will use that location to build valhalla tiles. The same goes for associate_segments.sh...it will use a mount point to get the latest version of the valhalla tiles.

**Comment by heffergm** [comment]
Rough requirements:

- [x] create empty ECS cluster
- [x] associate with Opsworks stack, which should approximate the following setup
  - [x] one r4.2xl
  - [x] EBS volumes for /data/valhalla (300gb), /var/lib/docker
  - [x] associate IAM role which permits the usual ECS actions
    - [x] add perms for S3 for whatever bucket ends up being used
- [x] create task definition for minutely planet updates
- [x] create ECS service to run `minutely_update.sh`
- [x] create lambda process to run cut_tiles.sh weekly
- [x] create Cloudwatch Logs groups for planet update and cut_tiles
  - [x] create metric filters for planet updates to show processing success/failure
  - [x] create metric filters for cut_tiles to show processing succss/failure
<strike>  - [ ] configure cloudwatch alarms for any of the above?</strike>
- [x] build [grafana dashboard](https://grafana.opentraffic.io/dashboard/db/valhalla-tiles?refresh=1m&orgId=1) for system metrics
- [x] merge associate_segments logic into cut_tiles.sh
- [x] test and confirm that the output of the scripts is correct
- [x] test download_tiles.sh (from reporter repository).  Confirm that it can use a bounding box to download the tiles from S3

**Comment by heffergm** [comment]
@gknisely progress thus far:

- I fixed one minor bug in the cut_tiles script and pushed the fix
- the lambda code and schedule is in place
- the last test run made it as far as processing nodes/ways from the planet pbf, then exited with the following:

```
2017/06/03 05:03:31.844756 [32;1m[INFO][0m Finished with 105325722 routable ways containing 1153658505 nodes
2017/06/03 05:03:31.844781 [32;1m[INFO][0m Sorting osm access tags by way id...
2017/06/03 05:03:31.844837 [32;1m[INFO][0m Parsing relations...
2017/06/03 05:28:01.324484 [32;1m[INFO][0m skipping restriction with vias > the max allowed. OSMID: 1414677
2017/06/03 05:28:01.324540 [32;1m[INFO][0m skipping restriction with vias > the max allowed. OSMID: 1414679
2017/06/03 05:28:43.611638 [32;1m[INFO][0m Finished with 653363 simple restrictions
2017/06/03 05:28:43.611658 [32;1m[INFO][0m Finished with 5 lane connections
2017/06/03 05:28:43.616357 [32;1m[INFO][0m Sorting complex restrictions by from id...
2017/06/03 05:28:43.617160 [32;1m[INFO][0m Sorting osm way node references by node id...
2017/06/03 05:33:52.530619 [32;1m[INFO][0m Finished
2017/06/03 05:33:52.530653 [32;1m[INFO][0m Parsing nodes...
terminate called after throwing an instance of 'std::runtime_error'
what(): Didn't find OSMWayNode for node id: 112
/scripts/cut_tiles.sh: line 127: 32 Aborted valhalla_build_tiles -c ${CONF_FILE} $(find ${EXTRACTS_DIR} -type f -name "*.pbf")
[FAILURE] Detected non zero exit status while processing valhalla tiles!
```

**Comment by gknisely** [comment]
Don't think there needs to be any cloudwatch alarms on data creation; however, @heffergm did set up a pager duty notification if it does fail.
