### ISSUE TITLE
Produce GeoJSON tiles in Web Mercator using ZXY scheme

### ISSUE THREAD

**Issue by drewda** [opentraffic/osmlr#32]
This generator application currently outputs GeoJSON in WGS84 using Valhalla's tile scheme. Some clients, like the [Open Traffic Analyst UI](https://github.com/opentraffic/analyst-ui), will more easily consume OSMLR GeoJSON geometries in Web Mercator using the `/zoom/x/y` tile scheme.

Questions on the generation side:
- Should the osmlr generator app cut these tiles itself? Or should a downstream process turn the existing WGS84 tiles in the Valhalla scheme into the Web Mercator ZXY tiles?
- In either case, can some code be reused from https://github.com/mapbox/tippecanoe https://github.com/mapbox/geojson-vt-cpp or https://github.com/mapbox/geojson-vt  ?

Questions on the consumer side:
- Is it sufficient to cut just one zoom level? Or should multiple be cut to support the different possible scales that a client may want to display?
- If multiple zoom levels are being cut, should simplification be applied at smaller-scale levels to reduce their file size?

//cc @dnesbitt61 @kevinkreiser @burritojustice @louh @meghanhade

**Comment by drewda** [comment]
A question from @bcamper: use TopoJSON instead of GeoJSON?

Currently, when a road goes two ways, there is an OSMLR segment for each direction, with duplicate GeoJSON geometries. Using [TopoJSON](https://github.com/topojson/topojson) could mean that the two OSMLR segments share one geometry. It would be up to clients to parse the TopoJSON tiles, find the appropriate arcs for each OSMLR segment, and render each segment/direction with offsets from the roadway centerline. So, smaller file size, but a tad more processing on write and read. Sounds worthwhile... assuming all these assumptions are valid.

**Comment by dnesbitt61** [comment]
There is not a guarantee that 2-directional OSMLR segments exactly match. In cases where segments are split (when greater than 1km) the logic may not always create equal, but opposing segment definitions.

**Comment by drewda** [comment]
@dnesbitt61 good to know. That wouldn't be a problem in TopoJSON -- those segments would continue to have separate geometries -- but would reduce its benefits in file size.

**Comment by kevinkreiser** [comment]
we actually dont even know which ones do exactly match. so in order to actually save on the size, we'd have to do the work to figure out which ones are exact copies but in the opposite direction.

**Comment by bcamper** [comment]
It's fine to just use GeoJSON if it's an issue.

**Comment by drewda** [comment]
No longer necessary because:

- We'll be able to power all static data products (https://github.com/opentraffic/datastore/issues/36) and the Analyst UI (https://github.com/opentraffic/analyst-ui/pull/16) using WGS84 geometries in the Valhalla tile scheme.

- Even if it's slightly more involved to load and project OSMLR segment geometries into Leaflet/Tangram, this means that all Open Traffic geometries and speeds/counts can be provided in the same tile scheme. Also it means the static data product pipeline (https://github.com/opentraffic/datastore/issues/37) can potentially produce public data extracts and Valhalla historical speed tiles at the same time, or at least using the same tile bounding boxes on input and output.

NOTE: We may still want to improve the process of creating OSMLR GeoJSON tiles -- it currently requires a separate run to create PBF and to create GeoJSON -- but this can be considered in the future along with #7
