### ISSUE TITLE
Consistent Splitting of Opposing OSMLR Segments

### ISSUE THREAD

**Issue by dnesbitt61** [opentraffic/osmlr#36]
Splitting segments over 1km long should occur at the same locations when there are opposing OSMLR segments (on 2-way driveable roads). Current logic moves in the forward direction and splits at appropriate locations such that no segment is over 1km long. 

For single edges that are over 1km long this can be made consistent by considering the direction (forward/reverse) of the directed edge compared to the edge shape.

For multiple edges where the split occurs at intersecting nodes a different approach is needed.

**Comment by zerebubuth** [comment]
Another possible algorithm: split at `length / ceil(length / 1000)` metre intervals, rather than at 1km. This is symmetric, so should result in the same segments in both directions.

**Comment by dnesbitt61** [comment]
Thanks!

**Comment by dnesbitt61** [comment]
Actually, for single edges that exceed the max length it already splits consistently:
      int n = (edge_len / kMaximumLength);
      float dist = static_cast<float>(edge_len) / static_cast<float>(n+1);

it does n iterations of trimming dist from the front of the shape, then outputs the remaining shape (the last dist along the shape). So this should be symmetric in the 2 directions of the edge.

**Comment by dnesbitt61** [comment]
I think this is done, given last comment edges exceeding max length are split at distances that should result in same segment cuts in forward and reverse direction
