### ISSUE TITLE
Opentraffic integration with Traccar

### ISSUE THREAD

**Issue by kirantpatil** [opentraffic/osmlr#5]
Hi,

When is this platform available for public testing.

To start with we need API to find the distance between locations and Time to reach with traffic data.

We want to integrate Opensource Distance and Time (including traffic) API instead of Google with Traccar app(https://github.com/tananaev/traccar/issues/2629#issuecomment-269040670) which is used for Fleet/logistic management in many countries.

With this integration we(Traccar and community) can contribute to Opentraffic in big way.

Regards,
Kiran.

**Comment by drewda** [comment]
@kirantpatil, thank you for your interest in Open Traffic! Please sign up for our newsletter, which will have more information when Open Traffic is available for wider testing: http://opentraffic.us14.list-manage.com/subscribe?u=0e6adfcd7ba2f8404e6ea92bc&id=8ab8b0910a

**Comment by kirantpatil** [comment]
@drewda, may I know what would be the tentative date of availability for wider testing.
